### ISSUE TITLE
Missing Lyrics Bug

### ISSUE THREAD

**Issue by yeemanbandito** [surfbryce/beautiful-lyrics#53]
For some odd reason the lyrics for most songs do not work sometimes. They sometimes appear when I play the song I want lyrics for, queue another song, then queue the first song. Sometimes just swapping songs constantly from a certain song to another fixes it for that song. Posting screenshots of one such instance. 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/88994676/301e417c-6699-4479-9b49-f10a010976fd)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/88994676/848bfa8b-c876-452c-bdb5-78e701ec71cb)

**Comment by Blankk02** [comment]
same

**Comment by Blankk02** [comment]
once it helped to change the song, but now for 12 hours nothing works with new songs

**Comment by Armagxtten** [comment]
yeah i also have this problem

**Comment by BtrayZ** [comment]
same here i cant see any lyrics

**Comment by Blankk02** [comment]
@surfbryce Any comment about this problem?

**Comment by surfbryce** [comment]
I don't have any explanation as of now because I can't replicate it - I plan to look at this later during the week.

**Comment by surfbryce** [comment]
I just put out a new update please let me know if this fixes it!

**Comment by deathrjj** [comment]
Doesn't seem to have fixed it for me, first time using the extension and it never shows lyrics 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/6403d70c-e3e2-43b7-aac5-6d8830f46e2e)

**Comment by deathrjj** [comment]
> Doesn't seem to have fixed it for me, first time using the extension and it never shows lyrics ![image](https://user-images.githubusercontent.com/7521286/251468934-6403d70c-e3e2-43b7-aac5-6d8830f46e2e.png)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/7f078ef8-e549-4aed-924c-062202dd71e4)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/2b868d87-ff81-4251-a5ae-7b1ab77ebe79)

I'm using these extensions, and my theme is Dribbblish incase something's conflicting.
Occurs 100% of the time for me so you might be able to replicate it

**Comment by deathrjj** [comment]
Using the latest versions:

Spotify for Windows (64 bit)
1.2.14.1149.ga3ae422d
Spicetify v2.20.3

**Comment by deathrjj** [comment]
@surfbryce ^^^ that might help you replicate it

**Comment by yeemanbandito** [comment]
> I just put out a new update please let me know if this fixes it!

Sadly it still seems to not show lyrics. On versions previous to the edits of the lyrics section of the sidebar I had little to no issues with it, but here a list of my downloaded items if that helps. Kinda weird if it's an incompatibility since nothing here really affects lyrics.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/88994676/ec329465-d181-4c5e-8900-5c9628761716)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/88994676/f2224920-6d5a-4940-aac6-52e3f105597d)

**Comment by Armagxtten** [comment]
strangely enough i opened the app for the first time today and it seemed to work perfectly then when i restarted it, none of the lyrics started to show up :/
i also have extensions that i dont think affect the lyrics?
Spotify for Windows (64 bit)
Windows 11 22H2
Spicetify Ver. 2.20.3

![2313123](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/d902a606-6f2f-4afd-ac25-bb693ea33fbd)
![111231](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/ecb673d6-b404-4f7e-866a-b7739a90f310)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/80ba14b1-baa3-4ab1-b8af-f34c84559617)

**Comment by surfbryce** [comment]
@yeemanbandito @Armagxtten @deathrjj Ok so I’m going to need more information - since it all looks like you’re on windows can run this command “spicetify apply enable-devtools” and then once it relaunches click the three dots in the top left corner and go to develop and open devtools. After that can you go to the console tab and screenshot everything there and send it to me! Thanks!

**Comment by deathrjj** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/d9f346bb-38e9-4cb3-b185-ec67afc09039)

@surfbryce This is the console after playing a song and enabling and disabling the lyrics page

**Comment by surfbryce** [comment]
> Using the latest versions:
> 
> Spotify for Windows (64 bit) 1.2.14.1149.ga3ae422d Spicetify v2.20.3

Try updating to the latest version of Spotify and see if that fixes it. I am on 1.2.15 but I don't know why that small version difference would make any change....

**Comment by surfbryce** [comment]
I'm going to try this on a Windows laptop today since this seems to be the platform with these issues - if I find anything peculiar I will let you guys know.

**Comment by Armagxtten** [comment]
this is my console tab when i tried changing songs and trying to load the lyrics 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/bac6bf14-05b5-4ff5-a632-8acaf4f71f6d)

**Comment by surfbryce** [comment]
Alright @deathrjj @Blankk02 @Armagxtten @yeemanbandito I think I've fixed the issue in version 3.0.8 - please let me know if it works for you properly now!

**Comment by surfbryce** [comment]
> this is my console tab when i tried changing songs and trying to load the lyrics
> 
> ![image](https://user-images.githubusercontent.com/71872569/251593075-bac6bf14-05b5-4ff5-a632-8acaf4f71f6d.png)

Actually this is a bigger issue than the one I just fixed; I'll take a look into it and see what I can do for that!

This is because I cache the lyrics but I cache them in one place and I guess the cache for that one place takes up more space than it's allowed. I'll work on a better solution for caching and have that updated soon!

**Comment by Armagxtten** [comment]
I got the new update, and it seems to work a bit better for me at least. Upon the first listen of a song it doesn't load the lyrics, but when I go back on the song it works normally. This is what my console also looks like going through songs and going back, also thanks for your hard work! It's really an amazing extension! ♡

![image](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/731bd7de-5532-4005-8546-92c66741811e)

**Comment by surfbryce** [comment]
> I got the new update, and it seems to work a bit better for me at least. Upon the first listen of a song it doesn't load the lyrics, but when I go back on the song it works normally. This is what my console also looks like going through songs and going back, also thanks for your hard work! It's really an amazing extension! ♡
> 
> ![image](https://user-images.githubusercontent.com/71872569/251597600-731bd7de-5532-4005-8546-92c66741811e.png)

yeah so this is going back to that caching thing I mentioned - I'm still working on fixing that but you should see a fix for this in about an hour

**Comment by deathrjj** [comment]
> 

Not sure why but seems like 1.2.14.1149 is the most recent I can get. I uninstalled Spotify and did a fresh install and it was still that version.

Using that fresh install with a blank installation of Spicetify and the 3.0.8 update with no other extensions installed I still cant get it to work at al.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/f798abfb-33d9-4310-8958-0c943e059706)

This is my console with fresh install of spotify, no other extensions and latest version @surfbryce

**Comment by surfbryce** [comment]
> > I got the new update, and it seems to work a bit better for me at least. Upon the first listen of a song it doesn't load the lyrics, but when I go back on the song it works normally. This is what my console also looks like going through songs and going back, also thanks for your hard work! It's really an amazing extension! ♡
> > ![image](https://user-images.githubusercontent.com/71872569/251597600-731bd7de-5532-4005-8546-92c66741811e.png)
> 
> yeah so this is going back to that caching thing I mentioned - I'm still working on fixing that but you should see a fix for this in about an hour

@Armagxtten I just put out an update, can you see if this fixes the issue? There shouldn't be anymore caching issues from now on.

**Comment by surfbryce** [comment]
> > 
> 
> Not sure why but seems like 1.2.14.1149 is the most recent I can get. I uninstalled Spotify and did a fresh install and it was still that version.
> 
> Using that fresh install with a blank installation of Spicetify and the 3.0.8 update with no other extensions installed I still cant get it to work at al.
> 
> ![image](https://user-images.githubusercontent.com/7521286/251606368-f798abfb-33d9-4310-8958-0c943e059706.png)
> 
> This is my console with fresh install of spotify, no other extensions and latest version @surfbryce

This is actually very weird because the main issue here now is that CORS is failing even though it should be working just fine. I did notice on my backend-server that I forgot to change the allowed domain from "*" (all domains) to the Spotify app one. So that might've been causing Spotify to not allow the request to go through.

Can you try running on the latest version of the extensions @deathrjj? Easiest way to do that if you don't want to wait for it to auto-update itself (it checks about every 5 minutes) is to just reload/restart Spotify.

**Comment by deathrjj** [comment]
On 3.0.9 Still not working 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/98323588-85f6-4a01-91b0-a9eaa2a865d2)

This is log @surfbryce

**Comment by deathrjj** [comment]
seems like an issue with CORS, can requests be changed to 'no-cors'? Seems like thats the fix but not sure if its possible.

Online I can only see people suggesting an extension for chrome which isnt possible for spotify, or changing the request to no-cors.

**Comment by deathrjj** [comment]
Unless installing chrome extensions on spotify client is possible? idk

**Comment by surfbryce** [comment]
> seems like an issue with CORS, can requests be changed to 'no-cors'? Seems like thats the fix but not sure if its possible.
> 
> Online I can only see people suggesting an extension for chrome which isnt possible for spotify, or changing the request to no-cors.

Well this issue I think is purely isolated to you at the moment, theoretically - my server returns back the appropriate CORS header that allows Spotify to make the request full-throttle.

The issue with setting a request to use "no-cors" is that because the browser (Spotify is basically just a Chrome browser packaged up as its own App) deems the request as unsafe - no data is returned. The request is simply made to the server and that's it. Which is useless in this scenario because I need lyrics from my server.

I would recommend reinstalling Spotify if possible. I also have a question are you using the Windows Store version or the one downloaded from the Website? I would recommend uninstalling Spotify and then installing from the Website to make sure.

This issue theoretically shouldn't even be possible so I have a feeling it's an issue with Spotify itself

**Comment by yeemanbandito** [comment]
hey, so i cant exactly say for sure if the update worked or if manually installing it did. i recently deleted the extension and had some issues downloading through marketplace so i placed the .js file from the github into the extensions folder of spicetify and wrote this into powershell. 

`spicetify config extensions beautiful-lyrics.js
spicetify apply`

as of now, i'm able to see lyrics. (apologies for the late response)

@surfbryce

**Comment by surfbryce** [comment]
@yeemanbandito Thanks for the response! Glad that this is working for you now! If any issues arise relating to this issue feel free to come back and write a comment about it.

Won't close this issue just yet until I hear back from everyone else - but I think it should work for everyone now that I've made some much needed updates

**Comment by deathrjj** [comment]
@surfbryce It's working! Thanks so much for the work you put into this
![image](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/be51920c-52f0-4aeb-8060-e52f1ca5271f)

Seems like the issue I was having was my VPN blocking it for some reason. Disabled the VPN and its working perfectly

**Comment by Armagxtten** [comment]
hey @surfbryce seems as if everything is working as intended now, thank you for your patience and your hard work <3

![image](https://github.com/surfbryce/beautiful-lyrics/assets/71872569/6422d8ed-619e-456c-81e3-a5bebb215c7b)

**Comment by surfbryce** [comment]
Glad to hear it! Thanks so much everyone for helping out with this whole process! Glad we've made it to a better product as a whole now - I'll be closing this - if any of you find any problems related to this please feel free to respond here and I'll reopen the issue and take a look at it 🥰

**Comment by deathrjj** [comment]
@surfbryce Thought you might wanna know, I fixed the issue with my work VPN, the CORS issue was being caused by a missing certificate. It now works flawlessly. Thanks for your work on this

**Comment by deathrjj** [comment]
![All monitors upgraded](https://github.com/surfbryce/beautiful-lyrics/assets/7521286/bc8b808c-bb33-45c3-b50f-6dfd09dcc8ea)
I've heavily customised windows, and themed spotify with your extension fits in great. I use the tiling window manager komorebi, yasb for the status bar, taskbarX for the taskbar, Files app on the Microsoft store as a replacement to explorer, customised windows terminal, a custom new tab / home page and many more

and now a sexy looking spotify client which fits perfectly (espeially when i play songs with purpley album art lol)
